//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealnetPortal.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DealnetPortal.Api.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string _10_Saved {
            get {
                return ResourceManager.GetString("_10_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        public static string _11_Quote {
            get {
                return ResourceManager.GetString("_11_Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        public static string _12_Submitted {
            get {
                return ResourceManager.GetString("_12_Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted .
        /// </summary>
        public static string _13_Submitted {
            get {
                return ResourceManager.GetString("_13_Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBR Warnings.
        /// </summary>
        public static string _14_CBRWarnings {
            get {
                return ResourceManager.GetString("_14_CBRWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBR Failure.
        /// </summary>
        public static string _16_CBRFailure {
            get {
                return ResourceManager.GetString("_16_CBRFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        public static string _18_Equipment {
            get {
                return ResourceManager.GetString("_18_Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit through automation.
        /// </summary>
        public static string _19_Submitthroughautomation {
            get {
                return ResourceManager.GetString("_19_Submitthroughautomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Review.
        /// </summary>
        public static string _20_CreditReview {
            get {
                return ResourceManager.GetString("_20_CreditReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Review (ECP).
        /// </summary>
        public static string _20_CreditReviewECP {
            get {
                return ResourceManager.GetString("_20_CreditReviewECP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIR .
        /// </summary>
        public static string _22_MIR {
            get {
                return ResourceManager.GetString("_22_MIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIR Blue Chip.
        /// </summary>
        public static string _22_MIRBlueChip {
            get {
                return ResourceManager.GetString("_22_MIRBlueChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIR Northstar.
        /// </summary>
        public static string _22_MIRNorthstar {
            get {
                return ResourceManager.GetString("_22_MIRNorthstar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Info (w/o email notice).
        /// </summary>
        public static string _22_MoreInfowoemailnotice {
            get {
                return ResourceManager.GetString("_22_MoreInfowoemailnotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIR Not Received.
        /// </summary>
        public static string _23_MIRNotReceived {
            get {
                return ResourceManager.GetString("_23_MIRNotReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Submitted.
        /// </summary>
        public static string _24_Re_Submitted {
            get {
                return ResourceManager.GetString("_24_Re_Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Submitted E.
        /// </summary>
        public static string _24_Re_SubmittedE {
            get {
                return ResourceManager.GetString("_24_Re_SubmittedE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined .
        /// </summary>
        public static string _25_Declined {
            get {
                return ResourceManager.GetString("_25_Declined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined Blue Chip.
        /// </summary>
        public static string _25_DeclinedBlueChip {
            get {
                return ResourceManager.GetString("_25_DeclinedBlueChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined Enable Deals.
        /// </summary>
        public static string _25_DeclinedEnableDeals {
            get {
                return ResourceManager.GetString("_25_DeclinedEnableDeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined Northstar.
        /// </summary>
        public static string _25_DeclinedNorthstar {
            get {
                return ResourceManager.GetString("_25_DeclinedNorthstar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined (wo/email notice).
        /// </summary>
        public static string _25_Declinedwoemailnotice {
            get {
                return ResourceManager.GetString("_25_Declinedwoemailnotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting Enbridge Approval.
        /// </summary>
        public static string _26_Pre_Approved {
            get {
                return ResourceManager.GetString("_26_Pre_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting Enbridge Approval.
        /// </summary>
        public static string _26_Pre_Approved15k {
            get {
                return ResourceManager.GetString("_26_Pre_Approved15k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting Enbridge Approval.
        /// </summary>
        public static string _26_Pre_ApprovedECP {
            get {
                return ResourceManager.GetString("_26_Pre_ApprovedECP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Review-Recommend Approval.
        /// </summary>
        public static string _27_FinalReview_RecommendApproval {
            get {
                return ResourceManager.GetString("_27_FinalReview_RecommendApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved .
        /// </summary>
        public static string _28_Approved {
            get {
                return ResourceManager.GetString("_28_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved $15k.
        /// </summary>
        public static string _28_Approved15k {
            get {
                return ResourceManager.GetString("_28_Approved15k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Blue Chip.
        /// </summary>
        public static string _28_ApprovedBlueChip {
            get {
                return ResourceManager.GetString("_28_ApprovedBlueChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved (Eco Energy).
        /// </summary>
        public static string _28_ApprovedEcoEnergy {
            get {
                return ResourceManager.GetString("_28_ApprovedEcoEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved (ECP).
        /// </summary>
        public static string _28_ApprovedECP {
            get {
                return ResourceManager.GetString("_28_ApprovedECP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Enable.
        /// </summary>
        public static string _28_ApprovedEnable {
            get {
                return ResourceManager.GetString("_28_ApprovedEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved (Enbridge).
        /// </summary>
        public static string _28_ApprovedEnbridge {
            get {
                return ResourceManager.GetString("_28_ApprovedEnbridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Northstar.
        /// </summary>
        public static string _28_ApprovedNorthstar {
            get {
                return ResourceManager.GetString("_28_ApprovedNorthstar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Northstar (w/o email).
        /// </summary>
        public static string _28_ApprovedNorthstarwoemail {
            get {
                return ResourceManager.GetString("_28_ApprovedNorthstarwoemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Second Look.
        /// </summary>
        public static string _28_ApprovedSecondLook {
            get {
                return ResourceManager.GetString("_28_ApprovedSecondLook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved (Utile Credit).
        /// </summary>
        public static string _28_ApprovedUtileCredit {
            get {
                return ResourceManager.GetString("_28_ApprovedUtileCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Vault.
        /// </summary>
        public static string _28_ApprovedVault {
            get {
                return ResourceManager.GetString("_28_ApprovedVault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved (wo/email notice).
        /// </summary>
        public static string _28_Approvedwoemailnotice {
            get {
                return ResourceManager.GetString("_28_Approvedwoemailnotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined (w/ou email notification).
        /// </summary>
        public static string _29_Declinedwouemailnotification {
            get {
                return ResourceManager.GetString("_29_Declinedwouemailnotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DW verbal approval.
        /// </summary>
        public static string _29_DWverbalapproval {
            get {
                return ResourceManager.GetString("_29_DWverbalapproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to Doc.
        /// </summary>
        public static string _30_ReadytoDoc {
            get {
                return ResourceManager.GetString("_30_ReadytoDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docs Out.
        /// </summary>
        public static string _31_DocsOut {
            get {
                return ResourceManager.GetString("_31_DocsOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docs Received.
        /// </summary>
        public static string _32_DocsReceived {
            get {
                return ResourceManager.GetString("_32_DocsReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docs Back Incomplete.
        /// </summary>
        public static string _34_DocsBackIncomplete {
            get {
                return ResourceManager.GetString("_34_DocsBackIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dead Deal.
        /// </summary>
        public static string _35_DeadDeal {
            get {
                return ResourceManager.GetString("_35_DeadDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Audit Call.
        /// </summary>
        public static string _37_PendingAuditCall {
            get {
                return ResourceManager.GetString("_37_PendingAuditCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting delivery.
        /// </summary>
        public static string _38_Awaitingdelivery {
            get {
                return ResourceManager.GetString("_38_Awaitingdelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal Funding Requested.
        /// </summary>
        public static string _40_DealFundingRequested {
            get {
                return ResourceManager.GetString("_40_DealFundingRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready for Audit.
        /// </summary>
        public static string _42_ReadyforAudit {
            get {
                return ResourceManager.GetString("_42_ReadyforAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funded-Syndicated.
        /// </summary>
        public static string _46_Funded_Syndicated {
            get {
                return ResourceManager.GetString("_46_Funded_Syndicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit in Progress.
        /// </summary>
        public static string _48_AuditinProgress {
            get {
                return ResourceManager.GetString("_48_AuditinProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funding Tomorrow.
        /// </summary>
        public static string _49_FundingTomorrow {
            get {
                return ResourceManager.GetString("_49_FundingTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audited Deficient.
        /// </summary>
        public static string _50_AuditedDeficient {
            get {
                return ResourceManager.GetString("_50_AuditedDeficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audited Awaiting TPV.
        /// </summary>
        public static string _51_AuditedAwaitingTPV {
            get {
                return ResourceManager.GetString("_51_AuditedAwaitingTPV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPV Confirmed.
        /// </summary>
        public static string _52_TPVConfirmed {
            get {
                return ResourceManager.GetString("_52_TPVConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPV Internal.
        /// </summary>
        public static string _53_TPVInternal {
            get {
                return ResourceManager.GetString("_53_TPVInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired Approval.
        /// </summary>
        public static string _84_ExpiredApproval {
            get {
                return ResourceManager.GetString("_84_ExpiredApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Changed Mind.
        /// </summary>
        public static string _85_CustomerChangedMind {
            get {
                return ResourceManager.GetString("_85_CustomerChangedMind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string _86_Cancelled {
            get {
                return ResourceManager.GetString("_86_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Line of Credit approval.
        /// </summary>
        public static string _90_MasterLineofCreditapproval {
            get {
                return ResourceManager.GetString("_90_MasterLineofCreditapproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminated.
        /// </summary>
        public static string _91_Terminated {
            get {
                return ResourceManager.GetString("_91_Terminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Blue Chip .
        /// </summary>
        public static string _ApprovedBlueChip {
            get {
                return ResourceManager.GetString("_ApprovedBlueChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booked.
        /// </summary>
        public static string _Booked {
            get {
                return ResourceManager.GetString("_Booked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string _Cancelled {
            get {
                return ResourceManager.GetString("_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditional Approval.
        /// </summary>
        public static string _ConditionalApproval {
            get {
                return ResourceManager.GetString("_ConditionalApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVC Confirmed.
        /// </summary>
        public static string _CVCConfirmed {
            get {
                return ResourceManager.GetString("_CVCConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVC Waiting to Fund.
        /// </summary>
        public static string _CVCWaitingtoFund {
            get {
                return ResourceManager.GetString("_CVCWaitingtoFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined Blue Chip.
        /// </summary>
        public static string _DeclinedBlueChip {
            get {
                return ResourceManager.GetString("_DeclinedBlueChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported.
        /// </summary>
        public static string _Exported {
            get {
                return ResourceManager.GetString("_Exported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Approved .
        /// </summary>
        public static string _Pre_Approved {
            get {
                return ResourceManager.GetString("_Pre_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved 10 K.
        /// </summary>
        public static string _Pre_Approved10K {
            get {
                return ResourceManager.GetString("_Pre_Approved10K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre Approved 15 K.
        /// </summary>
        public static string _Pre_Approved15K {
            get {
                return ResourceManager.GetString("_Pre_Approved15K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre Approved 20 K.
        /// </summary>
        public static string _PreApproved20K {
            get {
                return ResourceManager.GetString("_PreApproved20K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre Approved 5 K.
        /// </summary>
        public static string _PreApproved5K {
            get {
                return ResourceManager.GetString("_PreApproved5K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string _S_Approved {
            get {
                return ResourceManager.GetString("_S_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit review.
        /// </summary>
        public static string _S_Creditreview {
            get {
                return ResourceManager.GetString("_S_Creditreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dead.
        /// </summary>
        public static string _S_Dead {
            get {
                return ResourceManager.GetString("_S_Dead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined.
        /// </summary>
        public static string _S_Declined {
            get {
                return ResourceManager.GetString("_S_Declined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docs in.
        /// </summary>
        public static string _S_Docsin {
            get {
                return ResourceManager.GetString("_S_Docsin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docs out.
        /// </summary>
        public static string _S_Docsout {
            get {
                return ResourceManager.GetString("_S_Docsout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funded.
        /// </summary>
        public static string _S_Funded {
            get {
                return ResourceManager.GetString("_S_Funded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funding requested.
        /// </summary>
        public static string _S_Fundingrequested {
            get {
                return ResourceManager.GetString("_S_Fundingrequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More information.
        /// </summary>
        public static string _S_Moreinformation {
            get {
                return ResourceManager.GetString("_S_Moreinformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        public static string _S_Submitted {
            get {
                return ResourceManager.GetString("_S_Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Conditioner.
        /// </summary>
        public static string AirConditioner {
            get {
                return ResourceManager.GetString("AirConditioner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Filtration.
        /// </summary>
        public static string AirFiltration {
            get {
                return ResourceManager.GetString("AirFiltration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Handler.
        /// </summary>
        public static string AirHandler {
            get {
                return ResourceManager.GetString("AirHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and then you will be prompted to change the password..
        /// </summary>
        public static string AndThenYouPromptedToChangePass {
            get {
                return ResourceManager.GetString("AndThenYouPromptedToChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual.
        /// </summary>
        public static string Annual {
            get {
                return ResourceManager.GetString("Annual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application submitted.
        /// </summary>
        public static string ApplicationSubmitted {
            get {
                return ResourceManager.GetString("ApplicationSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basement Repair.
        /// </summary>
        public static string BasementRepair {
            get {
                return ResourceManager.GetString("BasementRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bathroom.
        /// </summary>
        public static string Bathroom {
            get {
                return ResourceManager.GetString("Bathroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boiler.
        /// </summary>
        public static string Boiler {
            get {
                return ResourceManager.GetString("Boiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker.
        /// </summary>
        public static string Broker {
            get {
                return ResourceManager.GetString("Broker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business phone.
        /// </summary>
        public static string BusinessPhone {
            get {
                return ResourceManager.GetString("BusinessPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BYID card.
        /// </summary>
        public static string ByidCard {
            get {
                return ResourceManager.GetString("ByidCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canadian National Institute for the Blind identification card.
        /// </summary>
        public static string CanadianBlindIdentificationCard {
            get {
                return ResourceManager.GetString("CanadianBlindIdentificationCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canadian citizenship card.
        /// </summary>
        public static string CanadianCitizenshipCard {
            get {
                return ResourceManager.GetString("CanadianCitizenshipCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canadian Military Family Identification Card.
        /// </summary>
        public static string CanadianFamilyMilitaryCard {
            get {
                return ResourceManager.GetString("CanadianFamilyMilitaryCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canadian Military Employment Card.
        /// </summary>
        public static string CanadianMilitaryCard {
            get {
                return ResourceManager.GetString("CanadianMilitaryCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canadian or foreign passport.
        /// </summary>
        public static string CanadianPassport {
            get {
                return ResourceManager.GetString("CanadianPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell phone.
        /// </summary>
        public static string CellPhone {
            get {
                return ResourceManager.GetString("CellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate of Indian Status.
        /// </summary>
        public static string CertificateInidanStatus {
            get {
                return ResourceManager.GetString("CertificateInidanStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void Cheque or Bank PAD Authorization Letter.
        /// </summary>
        public static string ChequeBankPAP {
            get {
                return ResourceManager.GetString("ChequeBankPAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client data inputted.
        /// </summary>
        public static string ClientDataInputted {
            get {
                return ResourceManager.GetString("ClientDataInputted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client’s comment.
        /// </summary>
        public static string ClientsComment {
            get {
                return ResourceManager.GetString("ClientsComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combi Boiler.
        /// </summary>
        public static string CombiBoiler {
            get {
                return ResourceManager.GetString("CombiBoiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment from customer.
        /// </summary>
        public static string CommentFromCustomer {
            get {
                return ResourceManager.GetString("CommentFromCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations.
        /// </summary>
        public static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer direct.
        /// </summary>
        public static string ConsumerDirect {
            get {
                return ResourceManager.GetString("ConsumerDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact information.
        /// </summary>
        public static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        public static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract was changed.
        /// </summary>
        public static string ContractChangedCancelledEsign {
            get {
                return ResourceManager.GetString("ContractChangedCancelledEsign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract ID.
        /// </summary>
        public static string ContractId {
            get {
                return ResourceManager.GetString("ContractId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract {0} was declined.
        /// </summary>
        public static string ContractWasDeclined {
            get {
                return ResourceManager.GetString("ContractWasDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract {0} was successfully changed.
        /// </summary>
        public static string ContractWasSuccessfullyChanged {
            get {
                return ResourceManager.GetString("ContractWasSuccessfullyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract {0} was successfully submitted.
        /// </summary>
        public static string ContractWasSuccessfullySubmitted {
            get {
                return ResourceManager.GetString("ContractWasSuccessfullySubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost of Borrowing.
        /// </summary>
        public static string CostOfBorrowing {
            get {
                return ResourceManager.GetString("CostOfBorrowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Application.
        /// </summary>
        public static string CreditApplication {
            get {
                return ResourceManager.GetString("CreditApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit check approved.
        /// </summary>
        public static string CreditCheckApproved {
            get {
                return ResourceManager.GetString("CreditCheckApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit check declined.
        /// </summary>
        public static string CreditCheckDeclined {
            get {
                return ResourceManager.GetString("CreditCheckDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit check initiated.
        /// </summary>
        public static string CreditCheckInitiated {
            get {
                return ResourceManager.GetString("CreditCheckInitiated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer First Name.
        /// </summary>
        public static string CustomerFirstName {
            get {
                return ResourceManager.GetString("CustomerFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Last Name.
        /// </summary>
        public static string CustomerLastName {
            get {
                return ResourceManager.GetString("CustomerLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer lead has not been accepted by any dealer for {0}h (type: {1}, postal code: {2}).
        /// </summary>
        public static string CustomerLeadHasNotBeenAcceptedByAnyDealerFor {
            get {
                return ResourceManager.GetString("CustomerLeadHasNotBeenAcceptedByAnyDealerFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer.
        /// </summary>
        public static string Dealer {
            get {
                return ResourceManager.GetString("Dealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer cancelled eSignature process.
        /// </summary>
        public static string DealerCancelledEsign {
            get {
                return ResourceManager.GetString("DealerCancelledEsign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Invoice Amount.
        /// </summary>
        public static string DealerInvoiceAmount {
            get {
                return ResourceManager.GetString("DealerInvoiceAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Profile Update.
        /// </summary>
        public static string DealerProfileUpdate {
            get {
                return ResourceManager.GetString("DealerProfileUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal Info.
        /// </summary>
        public static string DealInfo {
            get {
                return ResourceManager.GetString("DealInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deferral.
        /// </summary>
        public static string Deferral {
            get {
                return ResourceManager.GetString("Deferral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributor.
        /// </summary>
        public static string Distributor {
            get {
                return ResourceManager.GetString("Distributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doors.
        /// </summary>
        public static string Doors {
            get {
                return ResourceManager.GetString("Doors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door to door sales.
        /// </summary>
        public static string DoorToDoor {
            get {
                return ResourceManager.GetString("DoorToDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down Payment.
        /// </summary>
        public static string DownPayment {
            get {
                return ResourceManager.GetString("DownPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver’s license.
        /// </summary>
        public static string DriverLicense {
            get {
                return ResourceManager.GetString("DriverLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external login is already associated with an account..
        /// </summary>
        public static string EexternalLoginAlreadyAssociated {
            get {
                return ResourceManager.GetString("EexternalLoginAlreadyAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employed.
        /// </summary>
        public static string Employed {
            get {
                return ResourceManager.GetString("Employed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0% Equal Payments.
        /// </summary>
        public static string EqualPayments {
            get {
                return ResourceManager.GetString("EqualPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        public static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on Register user.
        /// </summary>
        public static string ErrorOnRegisterUser {
            get {
                return ResourceManager.GetString("ErrorOnRegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Warranty Form.
        /// </summary>
        public static string ExtendedWarrantyForm {
            get {
                return ResourceManager.GetString("ExtendedWarrantyForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External login failure..
        /// </summary>
        public static string ExternalLoginFailure {
            get {
                return ResourceManager.GetString("ExternalLoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External service is unavailable.
        /// </summary>
        public static string ExternalServiceUnavailable {
            get {
                return ResourceManager.GetString("ExternalServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financing.
        /// </summary>
        public static string Financing {
            get {
                return ResourceManager.GetString("Financing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financing + Leasing.
        /// </summary>
        public static string FinancingLeasing {
            get {
                return ResourceManager.GetString("FinancingLeasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fireplace.
        /// </summary>
        public static string Fireplace {
            get {
                return ResourceManager.GetString("Fireplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Rate.
        /// </summary>
        public static string FixedRate {
            get {
                return ResourceManager.GetString("FixedRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flooring.
        /// </summary>
        public static string Flooring {
            get {
                return ResourceManager.GetString("Flooring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following lead has not been accepted by any dealer for {0}h.
        /// </summary>
        public static string FollowingLeadHasNotBeenAcceptedByAnyDealerFor12h {
            get {
                return ResourceManager.GetString("FollowingLeadHasNotBeenAcceptedByAnyDealerFor12h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        public static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full time.
        /// </summary>
        public static string FullTime {
            get {
                return ResourceManager.GetString("FullTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funded Deals.
        /// </summary>
        public static string FundedDeals {
            get {
                return ResourceManager.GetString("FundedDeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furnace.
        /// </summary>
        public static string Furnace {
            get {
                return ResourceManager.GetString("Furnace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST.
        /// </summary>
        public static string Gst {
            get {
                return ResourceManager.GetString("Gst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST + PST.
        /// </summary>
        public static string GstPst {
            get {
                return ResourceManager.GetString("GstPst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST + QST.
        /// </summary>
        public static string GstQst {
            get {
                return ResourceManager.GetString("GstQst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat Pump.
        /// </summary>
        public static string HeatPump {
            get {
                return ResourceManager.GetString("HeatPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hepa System.
        /// </summary>
        public static string HepaSystem {
            get {
                return ResourceManager.GetString("HepaSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home improvement type.
        /// </summary>
        public static string HomeImprovementType {
            get {
                return ResourceManager.GetString("HomeImprovementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Owner&apos;s Name:.
        /// </summary>
        public static string HomeOwnersName {
            get {
                return ResourceManager.GetString("HomeOwnersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home phone.
        /// </summary>
        public static string HomePhone {
            get {
                return ResourceManager.GetString("HomePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Tub.
        /// </summary>
        public static string HotTub {
            get {
                return ResourceManager.GetString("HotTub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Water Heater (CV).
        /// </summary>
        public static string HotWaterHeaterCV {
            get {
                return ResourceManager.GetString("HotWaterHeaterCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Water Heater (PV).
        /// </summary>
        public static string HotWaterHeaterPV {
            get {
                return ResourceManager.GetString("HotWaterHeaterPV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly rate.
        /// </summary>
        public static string HourlyRate {
            get {
                return ResourceManager.GetString("HourlyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat Recovery Ventilator.
        /// </summary>
        public static string Hrv {
            get {
                return ResourceManager.GetString("Hrv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HST.
        /// </summary>
        public static string Hst {
            get {
                return ResourceManager.GetString("Hst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidifier with Furnace.
        /// </summary>
        public static string HumidifierWithFurnace {
            get {
                return ResourceManager.GetString("HumidifierWithFurnace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Water Tank.
        /// </summary>
        public static string Hwt {
            get {
                return ResourceManager.GetString("Hwt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Not yet generated.
        /// </summary>
        public static string IDNotYetGenerated {
            get {
                return ResourceManager.GetString("IDNotYetGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any question please contact.
        /// </summary>
        public static string IfYouHaveQuestionsPleaseContact {
            get {
                return ResourceManager.GetString("IfYouHaveQuestionsPleaseContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any question to home professional please contact.
        /// </summary>
        public static string IfYouHaveQuestionsToHomeProfessionalPleaseContact {
            get {
                return ResourceManager.GetString("IfYouHaveQuestionsToHomeProfessionalPleaseContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case of questions please contact.
        /// </summary>
        public static string InCaseOfQuestionsPleaseContact {
            get {
                return ResourceManager.GetString("InCaseOfQuestionsPleaseContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case remarks about selected home professionals please contact.
        /// </summary>
        public static string InCaseRemarksAboutSelectedHomeProfessionalsPleaseContact {
            get {
                return ResourceManager.GetString("InCaseRemarksAboutSelectedHomeProfessionalsPleaseContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income verification.
        /// </summary>
        public static string IncomeVerification {
            get {
                return ResourceManager.GetString("IncomeVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorporated.
        /// </summary>
        public static string Incorporated {
            get {
                return ResourceManager.GetString("Incorporated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Independent.
        /// </summary>
        public static string Independent {
            get {
                return ResourceManager.GetString("Independent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation address.
        /// </summary>
        public static string InstallationAddress {
            get {
                return ResourceManager.GetString("InstallationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user email..
        /// </summary>
        public static string InvalidUserEmail {
            get {
                return ResourceManager.GetString("InvalidUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitchen.
        /// </summary>
        public static string Kitchen {
            get {
                return ResourceManager.GetString("Kitchen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lease.
        /// </summary>
        public static string LeaseApplication {
            get {
                return ResourceManager.GetString("LeaseApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lease (HWT).
        /// </summary>
        public static string LeaseApplicationHwt {
            get {
                return ResourceManager.GetString("LeaseApplicationHwt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leasing.
        /// </summary>
        public static string Leasing {
            get {
                return ResourceManager.GetString("Leasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than 1 year.
        /// </summary>
        public static string LessThanOneYear {
            get {
                return ResourceManager.GetString("LessThanOneYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limited.
        /// </summary>
        public static string Limited {
            get {
                return ResourceManager.GetString("Limited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan.
        /// </summary>
        public static string LoanApplication {
            get {
                return ResourceManager.GetString("LoanApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Advertising.
        /// </summary>
        public static string LocalAds {
            get {
                return ResourceManager.GetString("LocalAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for secondary.
        /// </summary>
        public static string LookingForSecond {
            get {
                return ResourceManager.GetString("LookingForSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Filter (no stand alone units).
        /// </summary>
        public static string MediaFilterNSAU {
            get {
                return ResourceManager.GetString("MediaFilterNSAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile phone.
        /// </summary>
        public static string MobilePhone {
            get {
                return ResourceManager.GetString("MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Payment.
        /// </summary>
        public static string MonthlyPayment {
            get {
                return ResourceManager.GetString("MonthlyPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more than 2 years.
        /// </summary>
        public static string MoreThanTwoYears {
            get {
                return ResourceManager.GetString("MoreThanTwoYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New customer applied for financing.
        /// </summary>
        public static string NewCustomerAppliedForFinancing {
            get {
                return ResourceManager.GetString("NewCustomerAppliedForFinancing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No current financing solution.
        /// </summary>
        public static string NoCurrentFinancing {
            get {
                return ResourceManager.GetString("NoCurrentFinancing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No dealers matching customer lead (type: {0}, postal code: {1}).
        /// </summary>
        public static string NoDealersMatchingCustomerLead {
            get {
                return ResourceManager.GetString("NoDealersMatchingCustomerLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Interest.
        /// </summary>
        public static string NoInterest {
            get {
                return ResourceManager.GetString("NoInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEM.
        /// </summary>
        public static string OEM {
            get {
                return ResourceManager.GetString("OEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-2 years.
        /// </summary>
        public static string OneToTwoYears {
            get {
                return ResourceManager.GetString("OneToTwoYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on the.
        /// </summary>
        public static string OnThe {
            get {
                return ResourceManager.GetString("OnThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your on-time password is correct, now please change the password.
        /// </summary>
        public static string OntimePassCorrectNowChange {
            get {
                return ResourceManager.GetString("OntimePassCorrectNowChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possession and Acquisition License (PAL card).
        /// </summary>
        public static string PalCard {
            get {
                return ResourceManager.GetString("PalCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partnership.
        /// </summary>
        public static string Partnership {
            get {
                return ResourceManager.GetString("Partnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part time.
        /// </summary>
        public static string PartTime {
            get {
                return ResourceManager.GetString("PartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type.
        /// </summary>
        public static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Deals.
        /// </summary>
        public static string PendingDeals {
            get {
                return ResourceManager.GetString("PendingDeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent Residency Card.
        /// </summary>
        public static string PermanentResidencyCard {
            get {
                return ResourceManager.GetString("PermanentResidencyCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Sign Agreement.
        /// </summary>
        public static string PleaseSignAgreement {
            get {
                return ResourceManager.GetString("PleaseSignAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in using your email address and following password.
        /// </summary>
        public static string PleaseSignInUsingYourEmailAddressAndFollowingPassword {
            get {
                return ResourceManager.GetString("PleaseSignInUsingYourEmailAddressAndFollowingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use it to login the portal.
        /// </summary>
        public static string PleaseUseToLoginPortal {
            get {
                return ResourceManager.GetString("PleaseUseToLoginPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plumbing.
        /// </summary>
        public static string Plumbing {
            get {
                return ResourceManager.GetString("Plumbing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool.
        /// </summary>
        public static string Pool {
            get {
                return ResourceManager.GetString("Pool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porch Enclosure.
        /// </summary>
        public static string PorchEnclosure {
            get {
                return ResourceManager.GetString("PorchEnclosure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal Inquiries.
        /// </summary>
        public static string PortalInquiries {
            get {
                return ResourceManager.GetString("PortalInquiries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-approved.
        /// </summary>
        public static string PreApproved {
            get {
                return ResourceManager.GetString("PreApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred contact method.
        /// </summary>
        public static string PreferredContactMethod {
            get {
                return ResourceManager.GetString("PreferredContactMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prime.
        /// </summary>
        public static string Prime {
            get {
                return ResourceManager.GetString("Prime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prime Plus.
        /// </summary>
        public static string PrimePlus {
            get {
                return ResourceManager.GetString("PrimePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Inquiries.
        /// </summary>
        public static string ProgramInquiries {
            get {
                return ResourceManager.GetString("ProgramInquiries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proof of Insurance.
        /// </summary>
        public static string ProofOfInsurance {
            get {
                return ResourceManager.GetString("ProofOfInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referrals.
        /// </summary>
        public static string Referrals {
            get {
                return ResourceManager.GetString("Referrals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental.
        /// </summary>
        public static string RentalApplication {
            get {
                return ResourceManager.GetString("RentalApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental (HWT).
        /// </summary>
        public static string RentalApplicationHwt {
            get {
                return ResourceManager.GetString("RentalApplicationHwt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retired.
        /// </summary>
        public static string Retired {
            get {
                return ResourceManager.GetString("Retired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Osmosis (no stand alone units).
        /// </summary>
        public static string ReverseOsmosisNSAU {
            get {
                return ResourceManager.GetString("ReverseOsmosisNSAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roofing.
        /// </summary>
        public static string Roofing {
            get {
                return ResourceManager.GetString("Roofing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary/Income.
        /// </summary>
        public static string SalaryIncome {
            get {
                return ResourceManager.GetString("SalaryIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SalesRep.
        /// </summary>
        public static string SalesRep {
            get {
                return ResourceManager.GetString("SalesRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security System.
        /// </summary>
        public static string SecuritySystem {
            get {
                return ResourceManager.GetString("SecuritySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected type of service.
        /// </summary>
        public static string SelectedTypeOfService {
            get {
                return ResourceManager.GetString("SelectedTypeOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self employed.
        /// </summary>
        public static string SelfEmployed {
            get {
                return ResourceManager.GetString("SelfEmployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent to audit.
        /// </summary>
        public static string SentToAudit {
            get {
                return ResourceManager.GetString("SentToAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siding.
        /// </summary>
        public static string Siding {
            get {
                return ResourceManager.GetString("Siding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed Contract.
        /// </summary>
        public static string SignedContract {
            get {
                return ResourceManager.GetString("SignedContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed Installation Certificate.
        /// </summary>
        public static string SignedInstallationCertificate {
            get {
                return ResourceManager.GetString("SignedInstallationCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sole Prop.
        /// </summary>
        public static string SoleProp {
            get {
                return ResourceManager.GetString("SoleProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spa.
        /// </summary>
        public static string Spa {
            get {
                return ResourceManager.GetString("Spa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Rate.
        /// </summary>
        public static string StandardRate {
            get {
                return ResourceManager.GetString("StandardRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started to fill new contract.
        /// </summary>
        public static string StartedToFillNewContract {
            get {
                return ResourceManager.GetString("StartedToFillNewContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suite.
        /// </summary>
        public static string Suite {
            get {
                return ResourceManager.GetString("Suite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunrooms.
        /// </summary>
        public static string Sunrooms {
            get {
                return ResourceManager.GetString("Sunrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Prime.
        /// </summary>
        public static string SuperPrime {
            get {
                return ResourceManager.GetString("SuperPrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tankless Water Heater.
        /// </summary>
        public static string TanklessWaterHeater {
            get {
                return ResourceManager.GetString("TanklessWaterHeater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 or more.
        /// </summary>
        public static string TenOrMore {
            get {
                return ResourceManager.GetString("TenOrMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your interest in home improvement service.
        /// </summary>
        public static string ThanksForYourInterestInHomeImprovementService {
            get {
                return ResourceManager.GetString("ThanksForYourInterestInHomeImprovementService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for applying for financing..
        /// </summary>
        public static string ThankYouForApplyingForFinancing {
            get {
                return ResourceManager.GetString("ThankYouForApplyingForFinancing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no dealers matching following lead.
        /// </summary>
        public static string ThereAreNoDealersMatchingFollowingLead {
            get {
                return ResourceManager.GetString("ThereAreNoDealersMatchingFollowingLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Party Verification Call.
        /// </summary>
        public static string ThirdPartyVerificationCall {
            get {
                return ResourceManager.GetString("ThirdPartyVerificationCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your one-time password:.
        /// </summary>
        public static string ThisIsYourOnetimePass {
            get {
                return ResourceManager.GetString("ThisIsYourOnetimePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your password:.
        /// </summary>
        public static string ThisIsYourPass {
            get {
                return ResourceManager.GetString("ThisIsYourPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount Financed.
        /// </summary>
        public static string TotalAmountFinanced {
            get {
                return ResourceManager.GetString("TotalAmountFinanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Obligation.
        /// </summary>
        public static string TotalObligation {
            get {
                return ResourceManager.GetString("TotalObligation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Shows.
        /// </summary>
        public static string TradeShows {
            get {
                return ResourceManager.GetString("TradeShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction ID.
        /// </summary>
        public static string TransactionId {
            get {
                return ResourceManager.GetString("TransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Pieces of Equipment (water softener/carbon filter).
        /// </summary>
        public static string TwoPiecesofEquipmentWSCF {
            get {
                return ResourceManager.GetString("TwoPiecesofEquipmentWSCF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Application:.
        /// </summary>
        public static string TypeOfApplication {
            get {
                return ResourceManager.GetString("TypeOfApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unemployed.
        /// </summary>
        public static string Unemployed {
            get {
                return ResourceManager.GetString("Unemployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately this lead is no longer available.
        /// </summary>
        public static string UnfortunatelyThisLeadIsNoLongerAvailable {
            get {
                return ResourceManager.GetString("UnfortunatelyThisLeadIsNoLongerAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhappy with current solution.
        /// </summary>
        public static string UnhappyCurrentFinancing {
            get {
                return ResourceManager.GetString("UnhappyCurrentFinancing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown application to log in..
        /// </summary>
        public static string UnknownApplicationToLogIn {
            get {
                return ResourceManager.GetString("UnknownApplicationToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown application to register.
        /// </summary>
        public static string UnknownApplicationToRegister {
            get {
                return ResourceManager.GetString("UnknownApplicationToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password is incorrect..
        /// </summary>
        public static string UserNamerPasswordIncorrect {
            get {
                return ResourceManager.GetString("UserNamerPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Fan/HRV Combo.
        /// </summary>
        public static string VerticalFanHRVCombo {
            get {
                return ResourceManager.GetString("VerticalFanHRVCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void Cheque Bank PAD Authorization Letter.
        /// </summary>
        public static string VoidChequeBankPAPAuthorizationLetter {
            get {
                return ResourceManager.GetString("VoidChequeBankPAPAuthorizationLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy of Void Personal Cheque.
        /// </summary>
        public static string VoidPersonalChequeCopy {
            get {
                return ResourceManager.GetString("VoidPersonalChequeCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Filter.
        /// </summary>
        public static string WaterFilter {
            get {
                return ResourceManager.GetString("WaterFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Filter &amp; Water Softener.
        /// </summary>
        public static string WaterFilterWaterSoftener {
            get {
                return ResourceManager.GetString("WaterFilterWaterSoftener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Softener.
        /// </summary>
        public static string WaterSoftener {
            get {
                return ResourceManager.GetString("WaterSoftener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Treatment System.
        /// </summary>
        public static string WaterTreatmentSystem {
            get {
                return ResourceManager.GetString("WaterTreatmentSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’re looking for the best professional for your home improvement project.
        /// </summary>
        public static string WeAreLookingForTheBestProfessionalForYourHomeImprovementProject {
            get {
                return ResourceManager.GetString("WeAreLookingForTheBestProfessionalForYourHomeImprovementProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’re now looking for the best home professional in your area - selected contractor will contact you soon..
        /// </summary>
        public static string WeAreNowLookingForheBest {
            get {
                return ResourceManager.GetString("WeAreNowLookingForheBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We found home professional for your home improvement project.
        /// </summary>
        public static string WeFoundHomeProfessionalForYour {
            get {
                return ResourceManager.GetString("WeFoundHomeProfessionalForYour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We found home professional for your home improvement project.
        /// </summary>
        public static string WeFoundHomeProfessionalForYourHomeImprovementProject {
            get {
                return ResourceManager.GetString("WeFoundHomeProfessionalForYourHomeImprovementProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well Pump.
        /// </summary>
        public static string WellPump {
            get {
                return ResourceManager.GetString("WellPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole Home Combo.
        /// </summary>
        public static string WholeHomeCombo {
            get {
                return ResourceManager.GetString("WholeHomeCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} will contact you soon..
        /// </summary>
        public static string WillContactYouSoon {
            get {
                return ResourceManager.GetString("WillContactYouSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will contact you soon.
        /// </summary>
        public static string WillContactYouSoonText {
            get {
                return ResourceManager.GetString("WillContactYouSoonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string Windows {
            get {
                return ResourceManager.GetString("Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can view this deal here.
        /// </summary>
        public static string YouCanViewThisDealHere {
            get {
                return ResourceManager.GetString("YouCanViewThisDealHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can view your account on.
        /// </summary>
        public static string YouCanViewYourAccountOn {
            get {
                return ResourceManager.GetString("YouCanViewYourAccountOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been.
        /// </summary>
        public static string YouHaveBeen {
            get {
                return ResourceManager.GetString("YouHaveBeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been pre-approved for ${0}..
        /// </summary>
        public static string YouHaveBeenPreapprovedFor {
            get {
                return ResourceManager.GetString("YouHaveBeenPreapprovedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your financing application was successfully submitted..
        /// </summary>
        public static string YourFinancingApplicationWasSubmitted {
            get {
                return ResourceManager.GetString("YourFinancingApplicationWasSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your one-time password.
        /// </summary>
        public static string YourOneTimePassword {
            get {
                return ResourceManager.GetString("YourOneTimePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password.
        /// </summary>
        public static string YourPassword {
            get {
                return ResourceManager.GetString("YourPassword", resourceCulture);
            }
        }
    }
}
